Use PokeScrandle;

INSERT INTO Pokemon (Name) 
VALUES 
	('Bulbasaur'),
	('Ivysaur'),
	('Venusaur'),
	('Charmander'),
	('Charmeleon'),
	('Charizard'),
	('Squirtle'),
	('Wartortle'),
	('Blastoise'),
	('Caterpie'),
	('Metapod'),
	('Butterfree'),
	('Weedle'),
	('Kakuna'),
	('Beedrill'),
	('Pidgey'),
	('Pidgeotto'),
	('Pidgeot'),
	('Rattata'),
	('Radicate'),
	('Spearow'),
	('Fearow'),
	('Ekans'),
	('Arbok'),
	('Pikachu'),
	('Raichu'),
	('Sandshrew'),
	('Sandslash'),
	('Nidoran(F)'),
	('Nidorina'),
	('Nidoran(M)'),
	('Nidorino');